import {
  FaRegUserCircle,
  FaUserCircle,
  FaUserCheck,
  FaRegCopyright,
  FaGlobe,
  FaRegEye,
  FaRegEyeSlash,
  FaSpinner,
} from "react-icons/fa";
import {
  FaXTwitter,
  FaFacebook,
  FaSquareInstagram,
  Fa1,
  Fa2,
  Fa3,
  Fa4,
  Fa5,
  Fa6,
  Fa7,
  Fa8,
  Fa9,
  FaUserPlus,
} from "react-icons/fa6";
import { GoDot } from "react-icons/go";
import {
  IoIosClose,
  IoMdMoon,
  IoMdSunny,
  IoMdCheckmark,
  IoIosArrowBack,
  IoIosArrowForward,
} from "react-icons/io";
import { LuFileX, LuMonitor, LuSun, LuMoon, LuSend } from "react-icons/lu";
import {
  MdKeyboardArrowDown,
  MdKeyboardArrowUp,
  MdEmail,
} from "react-icons/md";
import { RiArrowGoBackFill, RiErrorWarningLine } from "react-icons/ri";
import { RxHamburgerMenu } from "react-icons/rx";
import { TbPaperBag } from "react-icons/tb";

export {
  FaRegUserCircle,
  FaUserCircle,
  FaUserCheck,
  FaXTwitter,
  FaFacebook,
  FaSquareInstagram,
  Fa1,
  Fa2,
  Fa3,
  Fa4,
  Fa5,
  Fa6,
  Fa7,
  Fa8,
  Fa9,
  FaUserPlus,
  FaRegCopyright,
  FaGlobe,
  FaRegEye,
  FaRegEyeSlash,
  FaSpinner,
  GoDot,
  LuFileX,
  LuMonitor,
  LuSun,
  LuMoon,
  LuSend,
  MdKeyboardArrowDown,
  MdKeyboardArrowUp,
  MdEmail,
  IoIosClose,
  IoMdMoon,
  IoMdSunny,
  IoMdCheckmark,
  IoIosArrowBack,
  IoIosArrowForward,
  RiArrowGoBackFill,
  RiErrorWarningLine,
  RxHamburgerMenu,
  TbPaperBag,
};
